"""create pokemons table

Revision ID: c36a60ebc256
Revises: 
Create Date: 2024-07-15 12:19:49.841982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c36a60ebc256'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('types', sa.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pokemons_id'), 'pokemons', ['id'], unique=False)
    op.create_index(op.f('ix_pokemons_name'), 'pokemons', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pokemons_name'), table_name='pokemons')
    op.drop_index(op.f('ix_pokemons_id'), table_name='pokemons')
    op.drop_table('pokemons')
    # ### end Alembic commands ###
